# Generated by Django 2.2.12 on 2020-06-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testi_name', models.CharField(max_length=100)),
                ('testi_desc', models.TextField()),
                ('testi_client', models.BooleanField(default=False)),
            ],
        ),
    ]
