# Generated by Django 2.2.12 on 2020-06-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0002_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_name', models.CharField(max_length=100)),
                ('abt_desc', models.TextField()),
                ('abt_img', models.ImageField(upload_to='abt_pics')),
                ('abt_course', models.IntegerField()),
                ('abt_students', models.IntegerField()),
                ('abt_teachers', models.IntegerField()),
                ('abt_countries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='about_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_card_name', models.CharField(max_length=100)),
                ('abt_card_desc', models.TextField()),
                ('abt_card_img', models.ImageField(upload_to='abt_pics')),
            ],
        ),
        migrations.CreateModel(
            name='about_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_team_name', models.CharField(max_length=100)),
                ('abt_team_desc', models.TextField()),
                ('abt_team_img', models.ImageField(upload_to='team')),
            ],
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
