# Generated by Django 2.2.12 on 2020-06-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0003_auto_20200609_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
