# Generated by Django 3.0.7 on 2020-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0004_auto_20200609_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header', models.CharField(max_length=100)),
                ('news_description', models.TextField()),
                ('news_img', models.ImageField(upload_to='news_pics')),
                ('news_date', models.DateField()),
            ],
        ),
    ]
