# Generated by Django 3.0.7 on 2020-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0005_category_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=100)),
                ('cont_email', models.EmailField(max_length=250)),
                ('cont_subject', models.CharField(max_length=250)),
                ('cont_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nl_name', models.CharField(max_length=100)),
                ('nl_email', models.EmailField(max_length=250)),
            ],
        ),
    ]
