# Generated by Django 3.0.7 on 2020-06-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0006_contact_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cont_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cont_msg',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cont_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cont_subject',
            new_name='Subject',
        ),
    ]
